"""empty message

Revision ID: 537d24973469
Revises: 
Create Date: 2023-09-29 08:58:53.355284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537d24973469'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statut_professionnel', sa.String(length=50), nullable=True),
    sa.Column('revenus_annuels_2023', sa.Float(), nullable=True),
    sa.Column('progression_annuelle', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('mode_versements', sa.String(length=10), nullable=True),
    sa.Column('versements_annee', sa.Float(), nullable=True),
    sa.Column('versements_proportionnels', sa.Float(), nullable=True),
    sa.Column('age_retraite', sa.Integer(), nullable=True),
    sa.Column('versements_fixes', sa.Float(), nullable=True),
    sa.Column('progression_annuelle_revenus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sujet', sa.String(length=200), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('expediteur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expediteur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('utilisateur')
    op.drop_table('etape')
    # ### end Alembic commands ###
